import { GoogleGenAI } from '@google/genai';
import { LabReport } from '../types/lab';

export interface GeminiClinicalReportResult {
  synthesisAr: string;
  synthesisEn: string;
  keyInsights: string[];
  recommendedFollowUps: string[];
  rawText: string;
}

/**
 * Generates an advanced clinical pathology synthesis using Gemini 3.8 Flash
 * through the modern @google/genai TypeScript SDK.
 */
export async function generateGeminiClinicalReport(
  report: LabReport
): Promise<GeminiClinicalReportResult | null> {
  const apiKey = (typeof process !== 'undefined' && process.env?.GEMINI_API_KEY) ||
    (typeof import.meta !== 'undefined' && (import.meta as any).env?.VITE_GEMINI_API_KEY) ||
    '';

  if (!apiKey) {
    console.warn('Gemini API key is not configured. Falling back to local clinical engine.');
    return null;
  }

  try {
    const ai = new GoogleGenAI({ apiKey });

    // Format laboratory tests for the AI prompt
    const patientInfo = `المريض: ${report.patient.fullName} | العمر: ${report.patient.age} سنة | الجنس: ${report.patient.gender === 'male' ? 'ذكر' : 'أنثى'} | رقم الملف: ${report.patient.labNumber}`;

    let testsSummary = '';
    report.profiles.forEach(prof => {
      testsSummary += `\n[بروفايل: ${prof.titleAr} (${prof.titleEn}) - نوع العينة: ${prof.sampleType}]\n`;
      prof.parameters.forEach(param => {
        const flagText = param.flag && param.flag !== 'NORMAL' ? ` [${param.flag}]` : '';
        testsSummary += `• ${param.name}: ${param.result} ${param.unit || ''} (المرجع: ${param.textReference || `${param.minNormal || ''}-${param.maxNormal || ''}`})${flagText}\n`;
      });
      if (prof.bloodFilmFindings) {
        testsSummary += `  * فحص الشريحة المجهري: RBC: ${prof.bloodFilmFindings.rbcMorphology || '-'}, WBC: ${prof.bloodFilmFindings.wbcMorphology || '-'}, Platelets: ${prof.bloodFilmFindings.plateletMorphology || '-'}\n`;
      }
    });

    const prompt = `أنت أ.د. رامي مختار - استشاري الباثولوجيا الإكلينيكية والكيميائية بكلية طب قصر العيني، جامعة القاهرة.
المطلوب إعداد تقرير طبي استشاري ذكي فائق الدقة والعمق لنتائج التحاليل المخبرية الآتية:

بيانات المريض:
${patientInfo}

نتائج الفحوصات المعملية:
${testsSummary}

يرجى تقديم تقرير استشاري سريري باللغتين العربية والإنجليزية يتضمن العناصر الآتية:
1. تقييم شامل لكافة الفحوصات الطبيعية وغير الطبيعية.
2. الربط الفسيولوجي والباثولوجي بين المؤشرات المرتفعة والمنخفضة (مثل مؤشرات صورة الدم، وظائف الكبد، الكلى، السكر، والدهون).
3. التشخيصات التفريقية الأكثر ترجيحاً (Differential Diagnoses) مع ذكر السند المخبري لكل تشخيص.
4. حساب المؤشرات السريرية الدقيقة (مثل مؤشر منتزر، معدل الترشيح الكبيبي eGFR، نسبة دي ريتيس، ومؤشر تصلب الشرايين).
5. خطة عمل وتوصيات استشارية محددة للطبيب المعالج والمريض (الفحوصات التكميلية الواجب إجراؤها والاستشارات التخصصية).

اجعل الأسلوب طبياً معتمداً ورصيناً يليق بأعلى معايير جودة المعامل الطبية المعتمدة ISO 15189.`;

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
      config: {
        systemInstruction: 'أنت استشاري باثولوجيا إكلينيكية وطب معملي ذو خبرة أكاديمية وسريرية واسعة. قدم تحليلاً طبياً دقيقاً ومفصلاً باللغتين العربية والإنجليزية.',
        temperature: 0.2
      }
    });

    const outputText = response.text || '';
    if (!outputText) return null;

    // Extract Arabic and English sections or parse key insights
    const paragraphs = outputText.split('\n\n').filter(p => p.trim().length > 0);
    const keyInsights: string[] = [];
    const recommendedFollowUps: string[] = [];

    // Parse bullet points
    outputText.split('\n').forEach(line => {
      const clean = line.replace(/^[•\-\*#\d\.]+\s*/, '').trim();
      if (!clean) return;
      if (line.includes('فحص') || line.includes('تحليل') || line.includes('يوصى') || line.includes('استشارة')) {
        if (clean.length > 15 && clean.length < 180) {
          recommendedFollowUps.push(clean);
        }
      } else if (line.includes('مؤشر') || line.includes('تشخيص') || line.includes('أنيميا') || line.includes('قصور') || line.includes('ارتفاع') || line.includes('انخفاض')) {
        if (clean.length > 15 && clean.length < 180) {
          keyInsights.push(clean);
        }
      }
    });

    return {
      synthesisAr: outputText,
      synthesisEn: 'Kasr Al Ainy Clinical Pathology Consultation generated by AI Studio Assistant for ' + report.patient.fullName,
      keyInsights: keyInsights.slice(0, 6),
      recommendedFollowUps: recommendedFollowUps.slice(0, 6),
      rawText: outputText
    };
  } catch (error) {
    console.warn('Gemini Clinical AI generation encountered an issue:', error);
    return null;
  }
}
